---
title: "2023-09-13 BAL asthma project update"
author: "youngjinkim"
date: "2023-09-13"
output: html_document
---

```{r setup, include=FALSE, fig.show='hide'}
knitr::opts_chunk$set(echo = TRUE)
if(file.exists(file.path(getwd(), "nasal_bronchial_BAL_rnaseq.R"))){
  source(file.path(getwd(), "nasal_bronchial_BAL_rnaseq.R"))
}

```

Most of the data do not have normal distribution
```{r data clean up}
x # count table
x3 # lcpm based on TMM
p.eos # metaData/phenotype
colnames(p.eos[,c(3,5,7,19)])
par(mfrow=c(2,2))
p.eos[,3]%>%qqnorm(main="Normal qqplot bal_Eos_ct_log")
p.eos[,5]%>%qqnorm(main="Normal qqplot BAL_Eos_perc_log")
p.eos[,7]%>%qqnorm(main="Normal qqplot BAL_WBC_log")
p.eos[,19]%>%qqnorm(main="Normal qqplot serum_Eos_log")

```

check for segregation by age, race, batch, Eos%
```{r mds by limma}
par(mfrow=c(2,2))
mds.eos<-plotMDS(lcpm.x3,  col= col$eos, labels=p.eos$BAL_Eos_perc, main="Eos %")
mds.batch<-plotMDS(lcpm.x3,  col= col$batch, labels=p.eos$Batch, main="batch")
mds.age<-plotMDS(lcpm.x3,  col= col$age, labels=p.eos$Age, main = "age")
mds.race<-plotMDS(lcpm.x3,  col= col$race, labels=p.eos$Race_corrected, main = "race")
```

```{r MDS with DESeq2}
vsdata <- vst(dds, blind=FALSE)
plotPCA(vsdata, intgroup="Batch") 
```

DEG done with Limma and Voom using various continuous variables with batch control
```{r DEG with Limma and voom, model with BAL Eos percentage}
mm2<-model.matrix(~0+bal.eos.log + batch)
mm2.1<-model.matrix(~bal.eos.log + batch)
drop2<-dropCutoff(0)
y2<-voom(x3[-drop2,], mm2, plot=T)
fit<-lmFit(y2,mm2)
tmp<-contrasts.fit(fit, coef=1)
tmp<-eBayes(tmp)
top.table2<-topTable(tmp,coef=1,sort.by="p", n = Inf)
head(top.table2, 20)
length(which(top.table2$adj.P.Val < 0.05))
# write.csv(top.table,file.path(getwd(),"output/",paste0("toptable_balEosPerc_",Sys.Date(),".csv")))

```

```{r DEG with Limma and voom, model with absolute BAL Eos count}
mm3<-model.matrix(~bal.eos.ct + batch)
drop2<-dropCutoff(0)
y3<-voom(x3[-drop2,], mm3, plot=T)
fit<-lmFit(y3,mm3)
tmp<-contrasts.fit(fit, coef=2)
tmp<-eBayes(tmp)
top.table3<-topTable(tmp,coef=1,sort.by="p", n = Inf)
head(top.table3, 20)
length(which(top.table3$adj.P.Val < 0.05))
# write.csv(top.table,file.path(getwd(),"output/",paste0("toptable_balEos_count_",Sys.Date(),".csv")))
```

```{r DEG with Limma Voom, model with absolute BAL WBC count}
mm4<-model.matrix(~bal.wbc + batch)
y4<-voom(x3[-drop2,], mm4, plot=T)
fit<-lmFit(y4,mm4)
tmp<-contrasts.fit(fit, coef=2)
tmp<-eBayes(tmp)
top.table4<-topTable(tmp,coef=1,sort.by="p", n = Inf)
head(top.table4, 20)
length(which(top.table4$adj.P.Val < 0.05))
# write.csv(top.table,file.path(getwd(),"output/",paste0("toptable_bal_WBC_",Sys.Date(),".csv")))
```

DEG done with DESeq2 using various continuous variables with batch control
```{r DEG with DEseq2, analyze based on log transformed BAL Eos %} 

dds<-DESeqDataSetFromMatrix(countData = x,colData=p.eos, design=~BAL_Eos_perc_log+Batch)
dds<-DESeq(dds)
res<-results(dds, name=c("BAL_Eos_perc_log"))
res <- res[order(res$padj),]
head(res)
# signficant results with padj<0.05
res.sig<-res[which(res$padj<0.05),]
res.sig
# write.csv(res.sig,file.path(getwd(),"output/",paste0("Deseq2_balEosPerc_",Sys.Date(),".csv")))

par(mfrow=c(1,1))
# Make a basic volcano plot
with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-3,3)))

# Add colored points: blue if padj<0.01, red if log2FC>1 and padj<0.05)
with(subset(res, padj<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
with(subset(res, padj<.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
```

```{r DEG with DEseq2, analyze based on log transformed BAL Eos Count}
dds2<-DESeqDataSetFromMatrix(countData = x,colData=p.eos, design=~bal_Eos_ct_log+Batch)
dds2<-DESeq(dds2)
res2<-results(dds2, name=c("bal_Eos_ct_log"))
res2 <- res2[order(res2$padj),]
head(res2)

# signficant results with padj<0.05
res.sig2<-res2[which(res2$padj<0.05),]
res.sig2

# write.csv(res.sig2,file.path(getwd(),"output/",paste0("Deseq2_balEos_ct_",Sys.Date(),".csv")))


par(mfrow=c(1,1))
# Make a basic volcano plot
with(res2, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-3,3)))

# Add colored points: blue if padj<0.01, red if log2FC>1 and padj<0.05)
with(subset(res2, padj<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
with(subset(res2, padj<.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
```

```{r DEG with DESeq2, analyze based on log transformed BAL WBC Count}
dds3<-DESeqDataSetFromMatrix(countData = x,colData=p.eos, design=~BAL_WBC_log+Batch)
dds3<-DESeq(dds3)
res3<-results(dds3, name=c("BAL_WBC_log"))
res3 <- res3[order(res3$padj),]
head(res3)

# signficant results with padj<0.05
res.sig3<-res3[which(res3$padj<0.05),]
res.sig3

# write.csv(res.sig2,file.path(getwd(),"output/",paste0("Deseq2_bal_WBC_ct_",Sys.Date(),".csv")))


par(mfrow=c(1,1))
# Make a basic volcano plot
with(res3, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-3,3)))

# Add colored points: blue if padj<0.01, red if log2FC>1 and padj<0.05)
with(subset(res3, padj<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="green"))
with(subset(res3, padj<.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
```

```{r DEG with DESeq2 analyze based on serum Eos Count}
p.eos<-p.eos%>%mutate(serum_Eos_log=log(serum_Eos+0.001))
hasna<-which(p.eos$serum_Eos_log%>%is.na)
nona<-p.eos[-hasna,"SampleID"]
p.eos.rmna<-p.eos[-hasna,]
x.rmna<-x[,nona]

dds4<-DESeqDataSetFromMatrix(countData = x.rmna,colData=p.eos.rmna, design=~serum_Eos_log+Batch)
dds4<-DESeq(dds4)
res4<-results(dds4, name=c("serum_Eos_log"))
res4 <- res4[order(res4$padj),]
head(res4)

# signficant results with padj<0.05
res.sig4<-res4[which(res4$padj<0.05),]
res.sig4
res.sig4%>%nrow

# write.csv(res.sig4,file.path(getwd(),"output/",paste0("Deseq2_serEos_ct_",Sys.Date(),".csv")))


par(mfrow=c(1,1))

# Make a basic volcano plot
with(res4, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-3,3)))

# Add colored points: blue if padj<0.01, red if log2FC>1 and padj<0.05)
with(subset(res4, padj<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="green"))
with(subset(res4, padj<.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))

```

